words = ["merhaba", "iyi", "gun", "ev", "okul", "ogrenci", "kitap", "masa", "kalem", "bilgisayar",
    "programlama", "python", "program", "gelistirici", "veri", "analiz", "yazilim", "internet",
    "muzik", "film", "spor", "saglik", "tatil", "arkadas", "aile", "sevgi", "doga", "hayvan",
    "yemek", "kahve", "cay", "kahvalti", "aksam", "gece", "gunduz", "hafta", "ay", "yil",
    "hava", "sehir", "seyahat", "plaj", "dag", "orman", "gokyuzu", "gunes", "yagmur", "kar",
    "ruzgar", "sicak", "soguk", "renk", "mavi", "yesil", "kirmizi", "sari", "siyah", "beyaz",
    "renkli", "sayi", "harf", "kelime", "cumle", "paragraf", "sayfa", "kitaplik", "yazar",
    "sanat", "muze", "resim", "heykel", "tarih", "gecmis", "gelecek", "gunumuz", "medeniyet",
    "kultur", "teknoloji", "iletisim", "telefon", "kamera", "goruntu", "ses", "mesaj", "konuşma",
    "sesli", "sessiz", "sessizlik", "melodi", "ritim", "enstruman", "piyano", "gitar", "keman",
    "muzisyen", "sarki", "not", "akor", "gozluk", "kamera", "fotograf", "video", "goruntu",
    "belge", "dosya", "klasor", "hafiza", "disk", "cloud", "internet", "baglanti", "veri",
    "bilgi", "hiz", "kalite", "performans", "ekran", "klavye", "fare", "tus", "farepad",
    "tuslu", "dokunmatik", "ekran", "gosterge", "giris", "cikis", "anakart", "islemci", "bellek",
    "harddisk", "ssd", "grafik", "oyun", "oyuncu", "strateji", "macera", "savas", "oyuncağım",
    "masal", "destan", "eglence", "gulme", "neşe", "mutluluk", "uzuntu", "ask", "sevgi",
    "evlilik", "aile", "arkadaslik", "dostluk", "paylasim", "yardim", "dayanisma", "toplum",
    "insan", "birey", "grup", "egitim", "ogrenme", "ogretmen", "ogrenci", "ders", "sinav",
    "basari", "basarisizlik", "mezuniyet", "diploma", "universite", "okul", "kitap", "kirtasiye",
    "odev", "proje", "arastirma", "konferans", "toplanti", "takvim", "saat", "zaman", "gecmis",
    "gelecek", "an", "saniye", "dakika", "saat", "gun", "hafta", "ay", "yil", "tatil", "izin",
    "tur", "gezi", "seyahat", "araç", "bisiklet", "yuruyus", "kosu", "spor", "fitness",
    "saglik", "hasta", "ilac", "doktor", "hastane", "tedavi", "diyet", "beslenme", "yemek",
    "icecek", "kahve", "cay", "su", "meyve", "sebze", "salata", "tatli", "çikolata",
    "kahvalti", "aksam", "gece", "yatak", "uyku", "ruya", "kabus", "gercek", "hayal",
    "film", "dizi", "kitap", "muzik", "oyun", "sanat", "gosteri", "konser", "tiyatro",
    "festival", "etkinlik", "organizasyon", "parti", "dugun", "dogum gunu", "kutlama",
    "hediye", "tebrik", "cicek", "balon", "gokyuzu", "gunes", "ay", "yildiz", "gece",
    "gunduz", "hava", "doga", "orman", "deniz", "gol", "nehir", "dag", "cöl", "orman",
    "plaj", "park", "cicek", "agac", "bitki", "hayvan", "kus", "balik", "kedi", "kopek",
    "at", "esek", "inek", "koyun", "tavuk", "ordek", "kurt", "ayi", "kaplan", "fil",
    "zebra", "aslan", "kaplumbaga", "maymun", "penguen", "zebra", "gergedan", "aslan", "kaplan",
    "fil", "kurt", "zürafa", "yilan", "kurbağa", "timsah", "ari", "kelebek", "ormansit",
    "sinek", "kertenkele", "kaplumbaga", "kus", "balik", "kopek", "kedi", "fare", "tavuk",
    "koyun", "inek", "at", "esek", "aslan", "kaplan", "fil", "zürafa", "maymun",
    "kis", "yarim", "kayisi", "kok", "peruk", "patates", "doner", "fayton",]